/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.svir.func.ui;

import java.awt.CardLayout;

import com.svir.func.ui.FunctionEditorAlgebraic;
import com.svir.func.ui.FunctionEditorPoints;

/**
 *
 * @author sleeplynerd
 */
public class FunctionEditor extends javax.swing.JFrame {
    
    private final String FUNCTION_DETAILS_CARD_ALGEBRAIC = "Algebraic";
    private final String FUNCTION_DETAILS_CARD_POINTS = "Points";
    /**
     * Creates new form FunctionEditor
     */
    public FunctionEditor() {
        initComponents();
        
        functionTypeComboBox.removeAllItems();
        functionTypeComboBox.addItem(FUNCTION_DETAILS_CARD_ALGEBRAIC);
        functionTypeComboBox.addItem(FUNCTION_DETAILS_CARD_POINTS);
        
        functionDetailsPanelCards.setLayout(new CardLayout());
        functionDetailsPanelCards.add(new FunctionEditorAlgebraic(), FUNCTION_DETAILS_CARD_ALGEBRAIC);
        functionDetailsPanelCards.add(new FunctionEditorPoints(), FUNCTION_DETAILS_CARD_POINTS);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rootSplit = new javax.swing.JSplitPane();
        leftSplit = new javax.swing.JSplitPane();
        functionsListScrollPane = new javax.swing.JScrollPane();
        fragmentList = new javax.swing.JList<>();
        functionDetailsPanel = new javax.swing.JPanel();
        functionTypeComboBox = new javax.swing.JComboBox<>();
        functionDetailsPanelCards = new javax.swing.JPanel();
        plotPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        leftSplit.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        fragmentList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        functionsListScrollPane.setViewportView(fragmentList);

        leftSplit.setTopComponent(functionsListScrollPane);

        functionDetailsPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        functionTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        functionTypeComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                functionTypeComboBoxItemStateChanged(evt);
            }
        });

        functionDetailsPanelCards.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout functionDetailsPanelLayout = new javax.swing.GroupLayout(functionDetailsPanel);
        functionDetailsPanel.setLayout(functionDetailsPanelLayout);
        functionDetailsPanelLayout.setHorizontalGroup(
            functionDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(functionTypeComboBox, 0, 120, Short.MAX_VALUE)
            .addComponent(functionDetailsPanelCards, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        functionDetailsPanelLayout.setVerticalGroup(
            functionDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(functionDetailsPanelLayout.createSequentialGroup()
                .addComponent(functionTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(functionDetailsPanelCards, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        leftSplit.setRightComponent(functionDetailsPanel);

        rootSplit.setLeftComponent(leftSplit);

        javax.swing.GroupLayout plotPanelLayout = new javax.swing.GroupLayout(plotPanel);
        plotPanel.setLayout(plotPanelLayout);
        plotPanelLayout.setHorizontalGroup(
            plotPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 266, Short.MAX_VALUE)
        );
        plotPanelLayout.setVerticalGroup(
            plotPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );

        rootSplit.setRightComponent(plotPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rootSplit)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rootSplit)
        );

        rootSplit.getAccessibleContext().setAccessibleName("");
        rootSplit.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void functionTypeComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_functionTypeComboBoxItemStateChanged
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)(functionDetailsPanelCards.getLayout());
        cl.show(functionDetailsPanelCards, (String)evt.getItem());
    }//GEN-LAST:event_functionTypeComboBoxItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FunctionEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FunctionEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FunctionEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FunctionEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FunctionEditor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> fragmentList;
    private javax.swing.JPanel functionDetailsPanel;
    private javax.swing.JPanel functionDetailsPanelCards;
    private javax.swing.JComboBox<String> functionTypeComboBox;
    private javax.swing.JScrollPane functionsListScrollPane;
    private javax.swing.JSplitPane leftSplit;
    private javax.swing.JPanel plotPanel;
    private javax.swing.JSplitPane rootSplit;
    // End of variables declaration//GEN-END:variables
}
